default:
  image: nixos/nix:2.3
  before_script:
   - nix-env -iA cachix -f https://cachix.org/api/v1/install
   - cachix use w3fpkgs

stages:
   - build
   - test


rus-tester:
  stage: build
  script: nix-build release.nix -A rust-tester | cachix push w3fpkgs
  timeout: 1h

go-tester:
  stage: build
  script: nix-build release.nix -A go-tester | cachix push w3fpkgs
  timeout: 1h

cpp-tester:
  stage: build
  script: nix-build release.nix -A cpp-tester | cachix push w3fpkgs
  timeout: 1h


tests:
  stage: test
  script: nix-shell release-shell.nix --pure --run ./runtests.jl
