default:
  image: nixos/nix:2.3
  before_script:
   - nix-env --quiet -f https://cachix.org/api/v1/install -iA cachix
   - cachix use w3fpkgs


stages:
   - build
   - test


.build:
  stage: build
  script: nix-build release.nix -A ${CI_JOB_NAME} | cachix push w3fpkgs
  timeout: 15m

rust-tester:
  extends: .build
  timeout: 2h

go-tester:
  extends: .build

cpp-tester:
  extends: .build


.test:
  stage: test
  script: nix-shell release-shell.nix --quiet --pure --run "./run_${CI_JOB_NAME}_tests.jl verbose"
  timeout: 15m

scale_codec:
  extends: .test

state_trie:
  extends: .test

pdre_api:
  extends: .test

pdre_api_legacy:
  extends: .test
