default:
  image: nixos/nix:2.3
  before_script:
   - nix-env -iA cachix -f https://cachix.org/api/v1/install
   - cachix use w3fpkgs

stages:
   - build
   - test


rust-tester:
  stage: build
  script: nix-build release.nix -A rust-tester | cachix push w3fpkgs
  timeout: 1h

go-tester:
  stage: build
  script: nix-build release.nix -A go-tester | cachix push w3fpkgs
  timeout: 1h

cpp-tester:
  stage: build
  script: nix-build release.nix -A cpp-tester | cachix push w3fpkgs
  timeout: 1h


scale-codec:
  stage: test
  script: nix-shell release-shell.nix --pure --run "./run_scale_codec_tests.jl verbose"

state-trie:
  stage: test
  script: nix-shell release-shell.nix --pure --run "./run_state_trie_tests.jl verbose"

pdre-api:
  stage: test
  script: nix-shell release-shell.nix --pure --run "./run_pdre_api_tests.jl vebose"

pdre-api-legacy:
  stage: test
  script: nix-shell release-shell.nix --pure --run "./run_pdre_api_tests_legacy.jl verbose"
