default:
  image: nixos/nix:2.3
  before_script:
   - nix-env --quiet -f https://cachix.org/api/v1/install -iA cachix
   - cachix use w3fpkgs


stages:
   - build
   - test


.build:
  stage: build
  script: nix-build release.nix -A ${CI_JOB_NAME} | cachix push w3fpkgs
  timeout: 15m

substrate-adapter:
  extends: .build
  timeout: 2h

gossamer-adapter:
  extends: .build

kagome-adapter:
  extends: .build


.test:
  stage: test
  script: nix-shell release-shell.nix --quiet --pure --run "./check.jl ${CI_JOB_NAME}"
  timeout: 15m


substrate hostapi:
  extends: .test
  #  needs: ["substrate-adapter"]

substrate hostapi-legacy:
  extends: .test
  #  needs: ["substrate-adapter"]


kagome hostapi:
  extends: .test
  #  needs: ["kagome-adapter"]

kagome hostapi-legacy:
  extends: .test
  #  needs: ["kagome-adapter"]

kagome scale-codec:
  extends: .test
  #  needs: ["substrate-adapter", "kagome-adapter"]

kagome state-trie:
  extends: .test
  #  needs: ["substrate-adapter", "kagome-adapter"]


gossamer scale-codec:
  extends: .test
  #  needs: ["substrate-adapter", "gossamer-adapter"]

gossamer state-trie:
  extends: .test
  #  needs: ["substrate-adapter", "gossamer-adapter"]
