version: 2

jobs:
  runTests:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            apt update && apt install -y --no-install-recommends \
              build-essential \
              cmake \
              pkg-config \
              libssl-dev \
              git \
              clang \
              libclang-dev \
              wget \
              gcc-8 \
              g++-8 \
              golang \
              julia \
              python

            # Install toolchain required for Wasm
            rustup target add wasm32-unknown-unknown --toolchain nightly
            cargo install --git https://github.com/alexcrichton/wasm-gc

            # Set default gcc and g++ binaries to version 8
            ln -sf /usr/bin/gcc-8 /usr/bin/gcc
            ln -sf /usr/bin/g++-8 /usr/bin/g++

            # Debug statements
            echo "Language versions:"
            rustc --version
            clang --version
            gcc --version
            g++ --version
            julia --version
            python --version
      - run:
          name: run tests
          command: |
            ./run_tests.sh

workflows:
  version: 2
  tests:
    jobs:
      - runTests:
          filters:
            tags:
              only: /.*/
