version: 2

jobs:
  runTests:
    docker:
      - image: debian:bullseye
    resource_class: large
    steps:
      - run: apt update; apt install -y git
      - checkout
      - run:
          name: install deps
          command: |
            # Only install dependencies if code changed
            if ! git diff master.. --name-only --diff-filter=AMDR HEAD^ | grep -q ^test\/
            then
              echo "No test code changed, skipping dependencies..."
              exit 0
            fi

            echo "Test code changed, installing dependencies..."

            apt update && apt install -y --no-install-recommends \
              build-essential \
              make \
              pkg-config \
              libssl-dev \
              clang \
              libclang-dev \
              wget \
              gcc \
              g++ \
              golang \
              julia \
              python \
              curl

            # Install CMake
            wget https://github.com/Kitware/CMake/releases/download/v3.16.0-rc4/cmake-3.16.0-rc4-Linux-x86_64.sh
            chmod +x cmake-3.16.0-rc4-Linux-x86_64.sh
            ./cmake-3.16.0-rc4-Linux-x86_64.sh --skip-license --prefix=/usr/local

            # Install Rust
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source ~/.cargo/env
            rustup default nightly

            # Install toolchain required for Wasm
            rustup target add wasm32-unknown-unknown --toolchain nightly
            cargo install --git https://github.com/alexcrichton/wasm-gc

            # Debug statements
            echo "Toolchain versions:"
            rustc --version
            clang --version
            gcc --version
            g++ --version
            julia --version
            python --version
            cmake --version
      - run:
          name: run tests
          command: |
            # Only run tests if code changed
            if ! git diff master.. --name-only --diff-filter=AMDR HEAD^ | grep -q ^test\/
            then
              echo "No test code changed, skipping tests..."
            else
              echo "Test code changed, running tests..."
              ./run_tests.sh verbose
            fi

workflows:
  version: 2
  tests:
    jobs:
      - runTests:
          filters:
            tags:
              only: /.*/
