name: Polkadot Specification Testsuite on Nix

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        implementation: [ substrate, kagome, gossamer ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: w3fpkgs
        skipPush: true
    - uses: cachix/cachix-action@v6
      with:
        name: pdspec
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build ${{ matrix.implementation }}-adapter
      run: nix-build test/nix/release.nix -A ${{ matrix.implementation }}-adapter


  test:
    needs: build
    strategy:
      matrix:
        implementation: [ kagome, gossamer ]
        fixture: [ scale-codec, state-trie ]
    runs-on: ubuntu-latest
    env:
      TEST_ID: ${{ matrix.implementation }} ${{ matrix.fixture }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: pdspec
        skipPush: true
    - name: Run ${{ matrix.fixture }} fixture against ${{ matrix.implementation }}
      run: nix-shell test/nix/ci-shell.nix --quiet --pure --argstr jobid "$TEST_ID" --run "test/check.jl $TEST_ID"

  test-hostapi:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: pdspec
        skipPush: true
    - name: Run test fixture
      run: nix-shell test/nix/ci-shell.nix --quiet --pure --argstr jobid "substrate hostapi" --run "test/check.jl substrate hostapi"

  test-hostapi-legacy:
    needs: build
    strategy:
      matrix:
        implementation: [ substrate, kagome ]
    runs-on: ubuntu-latest
    env:
      TEST_ID: ${{ matrix.implementation }} hostapi-legacy
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: pdspec
        skipPush: true
    - name: Run hostapi-legacy fixture against ${{ matrix.implementation }}
      run: nix-shell test/nix/ci-shell.nix --quiet --pure --argstr jobid "$TEST_ID" --run "test/check.jl $TEST_ID"

